python = "3.11"

[options]
shared_env_name = "openblender"
health_check_timeout = 15

[dependencies]
ffmpeg = "*"

[target.linux-64.dependencies]
xorg-libsm = "*"

[cuda]
packages = [
    "dpvo_cuda",
    "torch-scatter",
    "detectron2",
    "torch-sparse",
    "torch-cluster",
    "pytorch3d",
    "gsplat",
    "nvdiffrast",
    "flex_gemm",
    "cumesh",
    "o_voxel",
    "nvdiffrec_render",
    "flash-attn",
    "sageattention",
    "spconv",
    "cumm",
]

[pypi-dependencies]
numpy = ">=1.26.0,<1.27.0"
pillow = ">=10.0.0"
opencv-python-headless = ">=4.9.0"
av = ">=13.0.0"
scipy = ">=1.11.0"
lightning = ">=2.0.0"
hydra-core = ">=1.3.2"
hydra-zen = "*"
hydra-colorlog = "*"
timm = ">=0.9.16"
einops = ">=0.6.0"
einops-exts = ">=0.0.4"
rich = ">=13.0.0"
termcolor = "*"
joblib = ">=1.2.0"
scikit-image = ">=0.23.1"
imageio = ">=2.36.0"
imageio-ffmpeg = ">=0.4.0"
ffmpeg-python = ">=0.2.0"
trimesh = "*"
fast-simplification = ">=0.1.0"
open3d = ">=0.18.0"
point-cloud-utils = ">=0.29.5"
xatlas = ">=0.0.9"
pyvista = ">=0.43.0"
pymeshfix = ">=0.16.0"
PyOpenGL = ">=3.1.0"
chumpy-fork = "*"
smplx = ">=0.1.28"
pycolmap = "*"
bvh = ">=0.3"
lapx = "*"
yacs = ">=0.1.8"
huggingface-hub = ">=0.30.0"
gdown = ">=5.2.0"
roma = ">=1.5.1"
dill = ">=0.3.6"
fvcore = "*"
transformers = ">=4.56.0"
diffusers = "*"
hf_transfer = "*"
hf_xet = "*"
braceexpand = "*"
webdataset = ">=0.2.0"
loguru = ">=0.7.2"
optree = ">=0.11.0"
pyrootutils = ">=1.0.4"
iopath = "*"
tabulate = "*"
portalocker = "*"
psutil = ">=5.9.0"
bpy = "==4.2"
comfy-aimdo = "*"
comfy-sparse-attn = "*"
safetensors = "*"
kornia = "*"
lpips = "*"
zstandard = ">=0.22.0"
easydict = ">=1.13"
tqdm = "*"
plyfile = "*"
utils3d = { git = "https://github.com/EasternJournalist/utils3d.git", rev = "3fab839f0be9931dac7c8488eb0e1600c236e183" }
addict = "*"
omegaconf = "*"
python-igraph = ">=1.0.0"
astor = ">=0.8.0"
seaborn = ">=0.13.0"
matplotlib = ">=3.9.0"
plotly = ">=5.24.0"
gradio = ">=4.44.0"
torchsde = "*"
ninja = ">=1.10.0"
jaxtyping = "*"
pccm = ">=0.4.16"
ccimport = ">=0.4.4"

[target.linux-64.pypi-dependencies]
pyrender = ">=0.1.45"
triton = ">=3.0.0"

[target.win-64.pypi-dependencies]
triton-windows = ">=3.5.0"
